#Configuracion del docker para conectar la base de datos postgres

# Versión del formato del archivo docker-compose.yml
version: '3'

# Define los servicios que componen tu aplicación
services:
  todosDB:                              # Nombre del servicio
    image: postgres:15.3                # Imagen de Docker a utilizar para este servicio
    container_name: todos-db            # Nombre del contenedor de Docker que se creará a partir de esta imagen
    restart: always                     # Política de reinicio del contenedor. "always" significa que el contenedor siempre se reiniciará si se detiene
    ports:
       - 5432:5432                       # Mapeo de puertos entre el host y el contenedor. El puerto 5432 del host se mapea al puerto 5432 del contenedor
    #  - 5433:5432                       # Tuve que cambiar el puerto de postgres debido a que mi Database local se conectaba en el puerto 5432, la solucion para poder conectar con la base de docker es usar el puerto 5433 en el host y mantener 5432 en docker 
    environment:                       # Variables de entorno para el contenedor. Estas se utilizan para configurar el servidor PostgreSQL dentro del contenedor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/posgresql/data  

#luego se ejecuta en consola en la direccion del directorio del proyecto el comado:
# >> docker compose up -d